import { Injectable } from '@nestjs/common';
import { InjectQueue, InjectFlowProducer } from '@nestjs/bullmq';
import { Queue, FlowProducer, Job } from 'bullmq';

/**
 * Sample service demonstrating how to add jobs to queues and flows.
 *
 * ## Queue basics
 *
 * A **queue** holds jobs that are processed by **workers** in order.
 * Jobs are added via `queue.add(name, data, opts?)` and processed
 * by a class annotated with `@Processor(queueName)` that extends `WorkerHost`.
 *
 * ## Flow basics
 *
 * A **flow** chains multiple jobs across one or more queues.
 * When the parent job completes, its children are automatically enqueued.
 * This enables multi-step pipelines without manual orchestration.
 *
 * ## Execution & retry
 *
 * ```
 * queue.add('send-email', { to: 'user@example.com' }, { attempts: 3 })
 *       │
 *       ▼
 *   BullMQ enqueues the job into Redis
 *       │
 *       ▼
 *   Worker picks up the job (FIFO by default)
 *       │
 *       ├── process() returns OK  →  job completed
 *       │
 *       └── process() throws      →  job fails
 *               │
 *               ├── attempts left →  retry after backoff delay
 *               │                    (exponential: 2s, 4s, 8s, ...)
 *               │
 *               └── no attempts left →  job moved to "failed" set
 *                                       (can be manually retried)
 * ```
 *
 * ## Retry strategies
 *
 * | Strategy | delay | Behavior |
 * |----------|-------|----------|
 * | Fixed    | `{ type: 'fixed', delay: 5000 }` | Wait 5s between retries |
 * | Exponential | `{ type: 'exponential', delay: 1000 }` | 1s, 2s, 4s, 8s, ... |
 *
 * @example
 * ```typescript
 * import { QueueService } from 'xnest-kit/queue';
 *
 * @Module({
 *   providers: [QueueService],
 * })
 * export class OrderModule {}
 *
 * // Then in your controller:
 * await this.queueService.dispatchOrderEmail(order);
 * ```
 */
@Injectable()
export class QueueService {
  constructor(
    /**
     * Inject the 'email' queue registered via QueueModule.forRoot().
     * Uses `@InjectQueue('email')` — the token resolves to `BullQueue_email`.
     */
    @InjectQueue('email')
    private readonly emailQueue: Queue,

    /**
     * Inject the 'order-pipeline' flow producer.
     * Flow producers let you create parent-child job chains.
     */
    @InjectFlowProducer('order-pipeline')
    private readonly orderFlow: FlowProducer,
  ) {}

  /**
   * Add a simple job to the email queue.
   *
   * The job will be picked up by a Worker (defined via @Processor('email'))
   * and processed as soon as a worker is available.
   *
   * @param to - Recipient email address.
   * @param subject - Email subject line.
   * @param body - Email body content.
   * @returns The created Job instance.
   *
   * @example
   * ```typescript
   * const job = await queueService.sendEmail(
   *   'user@example.com',
   *   'Welcome!',
   *   '<h1>Hello</h1>',
   * );
   * console.log(job.id); // auto-generated by BullMQ
   * ```
   */
  async sendEmail(to: string, subject: string, body: string): Promise<Job> {
    return this.emailQueue.add(
      'send-email',
      { to, subject, body },
      {
        attempts: 3,
        backoff: { type: 'exponential', delay: 2000 },
        removeOnComplete: { age: 3600 * 24 },
        removeOnFail: { age: 3600 * 24 * 7 },
      },
    );
  }

  /**
   * Add a delayed job to the email queue.
   *
   * The job will not be visible to workers until the delay has elapsed.
   * Useful for scheduled notifications, reminders, etc.
   *
   * @param to - Recipient email address.
   * @param delayMs - Delay in milliseconds before the job becomes active.
   * @returns The created Job instance.
   *
   * @example
   * ```typescript
   * // Send welcome email 1 hour after signup
   * await queueService.sendDelayedEmail('user@example.com', 3600_000);
   * ```
   */
  async sendDelayedEmail(to: string, delayMs: number): Promise<Job> {
    return this.emailQueue.add(
      'send-email',
      { to, subject: 'Welcome!', body: 'Thanks for signing up' },
      {
        delay: delayMs,
        attempts: 3,
        backoff: { type: 'fixed', delay: 5000 },
      },
    );
  }

  /**
   * Add a high-priority job that jumps ahead of other jobs.
   *
   * BullMQ processes jobs within the **same priority tier** in FIFO order.
   * Lower numbers = higher priority.
   *
   * @returns The created Job instance.
   *
   * @example
   * ```typescript
   * // Password reset email — process before batch newsletters
   * await queueService.sendPriorityEmail();
   * ```
   */
  async sendPriorityEmail(): Promise<Job> {
    return this.emailQueue.add(
      'send-email',
      { to: 'urgent@example.com', subject: 'Password Reset', body: '...' },
      {
        priority: 1,
        attempts: 5,
        backoff: { type: 'exponential', delay: 1000 },
      },
    );
  }

  /**
   * Add a job that repeats on a cron schedule.
   *
   * BullMQ uses **repeatable jobs** — only one instance exists per
   * `(queue, name, pattern)` combo at any time. Adding the same
   * repeatable job again updates the existing one.
   *
   * @returns The created Job instance.
   *
   * @example
   * ```typescript
   * // Daily digest email at 08:00
   * await queueService.scheduleDailyDigest();
   * ```
   */
  async scheduleDailyDigest(): Promise<Job> {
    return this.emailQueue.add(
      'daily-digest',
      { type: 'daily-newsletter' },
      {
        repeat: { pattern: '0 8 * * *' },
        attempts: 3,
        backoff: { type: 'fixed', delay: 60_000 },
      },
    );
  }

  /**
   * Remove a previously scheduled repeatable job.
   *
   * @returns boolean indicating whether the job was removed.
   */
  async removeDailyDigest(): Promise<boolean> {
    return this.emailQueue.removeRepeatable('daily-digest', {
      pattern: '0 8 * * *',
    });
  }

  /**
   * Execute a multi-step flow (job chain).
   *
   * A flow creates a parent job and one or more children.
   * When the parent completes successfully, each child is automatically
   * enqueued into its respective queue and processed by its own worker.
   *
   * Flow tree:
   * ```
   * place-order  (order queue)
   *   ├── charge-payment    (payment queue)
   *   └── reserve-inventory (inventory queue)
   * ```
   *
   * All three jobs run concurrently — `place-order` first,
   * then `charge-payment` and `reserve-inventory` in parallel.
   *
   * For sequential chains (step → step → step), nest children:
   * ```
   * parent
   *   └── step-1
   *          └── step-2
   *                 └── step-3
   * ```
   *
   * @param orderId - Unique order identifier.
   * @returns The flow producer result (parent job details).
   *
   * @example
   * ```typescript
   * const result = await queueService.placeOrder('ord_123');
   * console.log(result.job.id); // parent job ID
   * console.log(result.children); // child job IDs
   * ```
   */
  async placeOrder(orderId: string) {
    return this.orderFlow.add({
      name: 'place-order',
      queueName: 'order',
      data: { orderId },
      opts: {
        attempts: 3,
        backoff: { type: 'exponential', delay: 2000 },
      },
      children: [
        {
          name: 'charge-payment',
          data: { orderId, amount: 49.99 },
          queueName: 'payment',
          opts: {
            attempts: 5,
            backoff: { type: 'exponential', delay: 1000 },
          },
        },
        {
          name: 'reserve-inventory',
          data: { orderId, sku: 'PROD-001' },
          queueName: 'inventory',
          opts: {
            attempts: 3,
            backoff: { type: 'fixed', delay: 5000 },
          },
        },
      ],
    });
  }

  /**
   * Re-run a failed job by its ID.
   *
   * After a job exhausts all retry attempts, it moves to the "failed" set.
   * Use `retry()` to re-enqueue it with fresh attempts.
   *
   * @param jobId - The ID of the failed job.
   * @returns boolean indicating success.
   *
   * @example
   * ```typescript
   * // Manually retry a job after fixing the underlying issue
   * await queueService.retryFailedJob('job_abc123');
   * ```
   */
  async retryFailedJob(jobId: string): Promise<boolean> {
    const job = await this.emailQueue.getJob(jobId);
    if (!job) {
      throw new Error(`Job ${jobId} not found`);
    }
    await job.retry();
    return true;
  }

  /**
   * Retry all failed jobs in the queue.
   *
   * Useful after recovering from an infrastructure outage.
   *
   * @returns The number of jobs that were retried.
   *
   * @example
   * ```typescript
   * await queueService.retryAllFailed();
   * ```
   */
  async retryAllFailed(): Promise<number> {
    const failed = await this.emailQueue.getJobs(['failed']);
    await Promise.all(failed.map((job) => job.retry()));
    return failed.length;
  }

  /**
   * Get the current state of a job.
   *
   * States: `completed`, `failed`, `active`, `waiting`, `delayed`, `paused`.
   *
   * @param jobId - The job ID to inspect.
   * @returns The Job instance or null.
   */
  async getJobStatus(jobId: string): Promise<Job | null> {
    return this.emailQueue.getJob(jobId);
  }

  /**
   * Get queue metrics: waiting, active, completed, failed counts.
   *
   * @returns Queue metrics.
   *
   * @example
   * ```typescript
   * const metrics = await queueService.getQueueMetrics();
   * // { waiting: 12, active: 3, completed: 450, failed: 2, delayed: 0 }
   * ```
   */
  async getQueueMetrics() {
    const [waiting, active, completed, failed, delayed] = await Promise.all([
      this.emailQueue.getJobCountByTypes('waiting'),
      this.emailQueue.getJobCountByTypes('active'),
      this.emailQueue.getJobCountByTypes('completed'),
      this.emailQueue.getJobCountByTypes('failed'),
      this.emailQueue.getJobCountByTypes('delayed'),
    ]);

    return { waiting, active, completed, failed, delayed };
  }

  /**
   * Pause the queue — workers stop picking up new jobs.
   * Currently active jobs continue until completion.
   */
  async pauseQueue(): Promise<void> {
    await this.emailQueue.pause();
  }

  /**
   * Resume the queue — workers start picking up jobs again.
   */
  async resumeQueue(): Promise<void> {
    await this.emailQueue.resume();
  }
}
